---
title: "PH251D Fall 2018 - Project 1"
author: "FirstName MI LastName"
date: "10/29/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Create a project folder called `project1`. You will put all your Project 1 files in this folder. Download this Rmarkdown template (`PH251D2018_LastName_Project1.Rmd`) from this GitHub site: 

Use R Markdown to demonstrate the following skills:

## 1. Using the `source` function

Download the `problem1.R` file and save to the `project1` folder. Run
the program file (problem1.r) using the ‘source’ command. Show the R
code chunk and results below.


## 2. Read an ASCII data set

The Evans data set (`evans.txt`) is here: <https://github.com/taragonmd/data>.

Alternatively, here is the raw Evans data set: <https://raw.githubusercontent.com/taragonmd/data/master/evans.txt>.

Demonstrate reading the Evans data file (evans.txt) to create a data
frame, and use the `str` function to explore the structure of the data
set. Show the R code chunk and results below.

## 3. Discretizing a continuous variable into a categorical variable

Total cholesterol levels less than 200 milligrams per deciliter
(mg/dL) are considered desirable (**normal**) for adults. A reading
between 200 and 239 mg/dL is considered **borderline high** and a
reading of 240 mg/dL and above is considered **high**.[^1]

The Evan data dictionary is in Appendix D of the PHDSwR book.
Convert total cholesterol variable (`chl`) into a categorical
variable (factor) with the three levels described above.


[^1]: Source: https://www.medicalnewstoday.com/articles/315900.php


## 4. Working with dates and times

President John F. Kennedy was assassinated on "November 22,
1963". Convert this character string into a R date object. Show how to
use R to display (a) the Julian date; (b) the day of the week, and (c)
the week of the year.


## 5. Simple two-way analysis

Create a simple 2x2 table of smoking (`smk`) and coronary heart
disease (`chd`). Use the `fisher.test` on this 2x2 table and describe
your findings.

## 6. Write your own function

Now, write a function to calculate the odds ratio of your 2x2 table
above. 

## 7. Nested `for` loops

Write a nested `for` loops to create a mulitiplication table for the
numbers 1 to 10.

## 8. Create a simple graph

From the Evans data create a histogram of the total cholesterol (`chl`).
Label with a title and axis labels. Output to a PNG file using the
`png` function.


## 9. Display PNG file in your Rmarkdown document

Using Rmarkdown syntax, display the PNG you created above.


## 10. Using regular expressions

Here are the California counties: <https://github.com/taragonmd/data/blob/master/calcounty.txt>

Remove the "California" entry.

Use regular expressions to identify and display the County names that
start with two or three letters followed by a space (e.g., `"San "`).
